### ISSUE TITLE
☂️  Roadmap

### ISSUE THREAD

**Issue by SoYoung210** [SoYoung210/figeleton#5]
## figma plugin

- [ ] Support HTML Type
- [ ] Generated Skeleton Preview on figma plugin
- [ ] Add component name as dat attribute. (help debug)
- [ ] Customize Skeleton Component creation options for each figma node.
- [ ] 🚀  Extracting repeating patterns as components
- [ ] 🚀  Support other css syntax (e.g. styled-components, stitches.js...)
